In [9]:
import pandas as pd
import numpy as np
import math

In [10]:
def forward_contract(initial_spot_price, daily_interest_rate, 
                     spot_price_increase, num_periods):
    forward_price = initial_spot_price * ((1+daily_interest_rate) ** num_periods)
    long_cash_flows = []
    short_cash_flows = []
    spot_prices = []

    for day in range(1, num_periods + 1):
        spot_price = initial_spot_price + day * spot_price_increase
        spot_prices.append(spot_price)
        long_payoff = spot_price - forward_price
        short_payoff = forward_price - spot_price

        long_cash_flow = long_payoff * (1 + daily_interest_rate) ** (num_periods - day)
        short_cash_flow = short_payoff * (1 + daily_interest_rate) ** (num_periods - day)

        long_cash_flows.append(long_cash_flow)
        short_cash_flows.append(short_cash_flow)

    return long_cash_flows, short_cash_flows, spot_prices, forward_price

## Problem 1A

In [11]:
initial_spot_price = 100.0
daily_interest_rate = 0.01
spot_price_increase = 0
num_periods = 3

long_cash_flows, short_cash_flows, spot_prices, forward_price = forward_contract(initial_spot_price, 
                                                                                 daily_interest_rate, 
                                                                                 spot_price_increase, 
                                                                                 num_periods)

forwards_df = pd.DataFrame()
forwards_df['Spot Prices'] = spot_prices
forwards_df['Long Cash Flows'] = long_cash_flows
forwards_df['Short Cash Flows'] = short_cash_flows


print("\nFinal Profit")
print(spot_prices[-1] - forward_price)
forwards_df.head()

Final Profit
-3.0301000000000187

   Spot Prices  Long Cash Flows  Short Cash Flows
0        100.0        -3.091005          3.091005
1        100.0        -3.060401          3.060401
2        100.0        -3.030100          3.030100

In [12]:
forwards_df.tail()

   Spot Prices  Long Cash Flows  Short Cash Flows
0        100.0        -3.091005          3.091005
1        100.0        -3.060401          3.060401
2        100.0        -3.030100          3.030100

In [13]:
print("From the above example, the final profit in this example would be just over -$3.00. \nThis means, that to have this forward replication via futures, the spot price at maturity (T=3) would need to be at least $", (forward_price + (-1 * (spot_prices[-1] - forward_price))))

From the above example, the final profit in this example would be just over -$3.00.
This means, that to have this forward replication via futures, the spot price at maturity (T=3) would need to be at least $ 106.06020000000004

## Problem 1B

In [14]:
initial_spot_price = 100.0
daily_interest_rate = 0.001  # 0.1% daily interest rate
spot_price_increase = 1.0
num_periods = 100

long_cash_flows, short_cash_flows, spot_prices, forward_price = forward_contract(initial_spot_price, 
                                                                                 daily_interest_rate, 
                                                                                 spot_price_increase, 
                                                                                 num_periods)

forwards_df = pd.DataFrame()
forwards_df['Spot Prices'] = spot_prices
forwards_df['Long Cash Flows'] = long_cash_flows
forwards_df['Short Cash Flows'] = short_cash_flows


print("\nFinal Profit:")
print(spot_prices[-1] - forward_price)
forwards_df.head()

Final Profit:
89.48843022792441

   Spot Prices  Long Cash Flows  Short Cash Flows
0        101.0       -10.500884         10.500884
1        102.0        -9.387485          9.387485
2        103.0        -8.276300          8.276300
3        104.0        -7.167326          7.167326
4        105.0        -6.060559          6.060559

In [15]:
forwards_df.tail()

    Spot Prices  Long Cash Flows  Short Cash Flows
95        196.0        85.830897        -85.830897
96        197.0        86.748155        -86.748155
97        198.0        87.663495        -87.663495
98        199.0        88.576919        -88.576919
99        200.0        89.488430        -89.488430

## Problem 2A

In [25]:
# This function is just a modification of the forwards function from problem 1

def forward_contract_special(initial_spot_price, 
                             odd_periods_interest_rate, 
                             even_periods_interest_rate, 
                             num_periods):
    temp_spot_price = 100
    long_cash_flows = []
    short_cash_flows = []
    spot_prices = []
    forward_prices = []

    for day in range(1, num_periods + 1):
        if day % 2 == 1:
            interest_rate = odd_periods_interest_rate
        else:
            interest_rate = even_periods_interest_rate

        if day % 2 == 1:
            temp_spot_price = temp_spot_price + 1
            spot_prices.append(temp_spot_price)
        else:
            temp_spot_price = temp_spot_price - 1
            spot_prices.append(temp_spot_price)
        
        forward_price = initial_spot_price * ((1+interest_rate) ** (math.floor((num_periods - day)/2)))
        forward_prices.append(forward_price)

        long_payoff = temp_spot_price - forward_price
        short_payoff = forward_price - temp_spot_price

        long_cash_flow = long_payoff * (1 + interest_rate) ** day
        short_cash_flow = short_payoff * (1 + interest_rate) ** day

        long_cash_flows.append(long_cash_flow)
        short_cash_flows.append(short_cash_flow)

    return long_cash_flows, short_cash_flows, spot_prices, forward_prices

In [28]:
initial_spot_price = 100.0
odd_periods_interest_rate = 0.001
even_periods_interest_rate = 0.00
num_periods = 100

long_cash_flows, short_cash_flows, spot_prices, forward_prices = forward_contract_special(initial_spot_price, 
                                                                                          odd_periods_interest_rate, 
                                                                                          even_periods_interest_rate, 
                                                                                          num_periods)

final_payout_long = sum(long_cash_flows)
final_payout_short = sum(short_cash_flows)
#print(forward_prices)

print("Final Payout of the Strategy:", (forward_prices[0] - initial_spot_price))


forwards_df = pd.DataFrame()
forwards_df['Spot Prices'] = spot_prices
forwards_df['Long Cash Flows'] = long_cash_flows
forwards_df['Short Cash Flows'] = short_cash_flows
forwards_df

Final Payout of the Strategy: 5.019463779694846

    Spot Prices  Long Cash Flows  Short Cash Flows
0           101        -4.023483          4.023483
1           100         0.000000          0.000000
2           101        -3.926305          3.926305
3           100         0.000000          0.000000
4           101        -3.828826          3.828826
..          ...              ...               ...
95          100         0.000000          0.000000
96          101         0.991626         -0.991626
97          100         0.000000          0.000000
98          101         1.104012         -1.104012
99          100         0.000000          0.000000

[100 rows x 3 columns]

## Problem 2B

In [30]:
initial_spot_price = 100.0
odd_periods_interest_rate = 0.000
even_periods_interest_rate = 0.001
num_periods = 100

long_cash_flows, short_cash_flows, spot_prices, forward_prices = forward_contract_special(initial_spot_price, 
                                                                                          odd_periods_interest_rate, 
                                                                                          even_periods_interest_rate, 
                                                                                          num_periods)

final_payout_long = sum(long_cash_flows)
final_payout_short = sum(short_cash_flows)
final_payout = final_payout_long - final_payout_short

print("Final Payout of the Strategy:", (forward_prices[0] - initial_spot_price))


forwards_df = pd.DataFrame()
forwards_df['Spot Prices'] = spot_prices
forwards_df['Long Cash Flows'] = long_cash_flows
forwards_df['Short Cash Flows'] = short_cash_flows
forwards_df

Final Payout of the Strategy: 0.0

    Spot Prices  Long Cash Flows  Short Cash Flows
0           101         1.000000         -1.000000
1           100        -5.029508          5.029508
2           101         1.000000         -1.000000
3           100        -4.934237          4.934237
4           101         1.000000         -1.000000
..          ...              ...               ...
95          100        -0.220251          0.220251
96          101         1.000000         -1.000000
97          100        -0.110291          0.110291
98          101         1.000000         -1.000000
99          100         0.000000          0.000000

[100 rows x 3 columns]

## Problem 3

The answers to parts a. and b. of question 2 are different, and this makes sense due to the compounding nature of interest. In question 2a, we are applying the interest rate to the odd periods, when the interest rate is positive. This results in interest gains, so the payout will be higher. In 2b. the payout is lower, because we have a 0% interest rate when the price goes up, but an interest loss when the price goes down.

You can't implement this strategy without knowing the future interest rates, or at least you won't be able to optimize it. Predicted future rates might differ from the spot rates when those time periods are reached, so your payoff could vary.